#!/bin/bash

source ../../toolset/build.env


if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE lex.cma
                check
                $AMAKE main.cmo
                check
                $AMAKE ocamllex
                check
                ;;
        clean)  $AMAKE -C
                $RM parser.mli
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/ocamlsys
                $INSTALL -d $INSTALLDIR/ocamlsys/bin
                $INSTALL -C ocamllex $INSTALLDIR/ocamlsys/bin
                ;;
        
    esac
done

echo "Done."
