#!/bin/bash

#
# Build an archive
#

if [ "X$VAMDIR" = "X" ] 
then
	VAMDIR=/amoeba/Vam-1.5
fi


$VAMDIR/bin/vamrun -b $VAMDIR/ocamlsys/bin/ocamlc 	\
	-I $VAMDIR/interface			\
	-I $VAMDIR/lib				\
	-I $VAMDIR/ocamlsys/lib/ocaml		\
	-I $VAMDIR/ocamlsys/lib/ocaml/threads	\
	-I $VAMDIR/ocamlsys/lib/ocaml/sys	\
	-thread -a				\
	$@

