#!/bin/bash

source ../../toolset/build.env

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE xnc.cma 
                check
		$AMAKE xnc
		check
                ;;
        clean)  $AMAKE -C
                $RM interface/*
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/bin
		$INSTALL -C xnc $INSTALLDIR/bin
    esac
done
