#!/bin/bash

source ../../toolset/build.env
VAMDOC=$VAMDIR/src/vamdoc.mld

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE  
                check
                ;;
        clean)  $AMAKE -C
                $RM interface/*
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/lib
                $INSTALL -d $INSTALLDIR/interface
                $INSTALL -C buffer.cma $INSTALLDIR/lib
                $INSTALL -C libbuffer_ext.a $INSTALLDIR/lib
                $INSTALL -C interface/*.cmi $INSTALLDIR/interface   

    esac
done
