#!/bin/bash

source ../../toolset/build.env

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE vamtoploop.cma
                check
                $AMAKE vamrun
                check
                $AMAKE vam.byte
                check
                $AMAKE xvam.byte
                check
                ;;
        clean)  $AMAKE -C
                $RM interface/*
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/bin
                $INSTALL -d $INSTALLDIR/lib
                $INSTALL -d $INSTALLDIR/interface
                $INSTALL -C vamrun $INSTALLDIR/bin
                $INSTALL -C vam.byte $INSTALLDIR/bin
                $INSTALL -C xvam.byte $INSTALLDIR/bin
                $INSTALL -C vamtoploop.cma $INSTALLDIR/lib 
                $INSTALL -C interface/*.cmi $INSTALLDIR/interface   

    esac
done
