#!/bin/bash

source ../../toolset/build.env
VAMDOC=$VAMDIR/doc/VAM.mld

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE mandoc.cma 
                check
                ;;
        doc)
                $AMAKE mld
                check
                ./mld -html test.md -o test.html 
                $INSTALL -C mld $INSTALLDIR/bin
                $INSTALL -C mld $VAMDIR/bin
                check
                ;;      
        clean)  $AMAKE -C
                $RM interface/*
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/lib
                $INSTALL -d $INSTALLDIR/doc
                $INSTALL -d $INSTALLDIR/bin
                $INSTALL -d $INSTALLDIR/interface
                $INSTALL -C mandoc.cma $INSTALLDIR/lib
                $INSTALL -C interface/*.cmi $INSTALLDIR/interface   
                ;;
    esac
done
