#!/bin/bash

source ../../toolset/build.env

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    
                ;;
        clean)  
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/config
                $INSTALL -C $VAMDIR/src/system/vamboot/boot $INSTALLDIR/config
    esac
done
