#!/bin/bash

source ../../toolset/build.env

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE stdlib.cma
                check
                $AMAKE camlheader
                check
                $AMAKE camlheader_ur
                check
                $AMAKE std_exit.cmo
                check
                ;;
        clean)  $AMAKE -C
                $RM interface/*
                $RM camlheader
                $RM camlheader_ur
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/ocamlsys
                $INSTALL -d $INSTALLDIR/ocamlsys/lib
                $INSTALL -d $INSTALLDIR/ocamlsys/lib/ocaml
                $INSTALL -C stdlib.cma $INSTALLDIR/ocamlsys/lib/ocaml
                $INSTALL -C std_exit.cmo $INSTALLDIR/ocamlsys/lib/ocaml
                $INSTALL -C camlheader camlheader_ur        \
                            $INSTALLDIR/ocamlsys/lib/ocaml
                $INSTALL -C interface/*.cmi $INSTALLDIR/ocamlsys/lib/ocaml        
                $INSTALL -C $VAMDIR/src/ocaml/stdlib/*.mli \
                            $INSTALLDIR/ocamlsys/lib/ocaml
    esac
done
