#!/bin/bash

source ../../toolset/build.env

if [ $# = 0 ]
then
    echo "Usage: build <targets>"
    echo "Targets: all clean install"
    exit 1
fi

check ()
{
    if [ $? != 0 ]
    then
        echo "Abort due to errors building target."
        exit 1
    fi
}


for TARGET in $@
do
    echo "Building target [$TARGET] ..."
    case $TARGET in
        all)    $AMAKE parsers.cmo
                check
                $AMAKE xlib.cma
                check
                $AMAKE xcom.cma
                check
                $AMAKE wxlib.cma
                check
                ;;
        clean)  $AMAKE -C
                $RM interface/*
                ;;
        install)    
                $INSTALL -d $INSTALLDIR/lib
                $INSTALL -d $INSTALLDIR/interface
                $INSTALL -C xlib.cma $INSTALLDIR/lib
                $INSTALL -C xcom.cma $INSTALLDIR/lib
                $INSTALL -C wxlib.cma $INSTALLDIR/lib
                $INSTALL -C interface/*.cmi $INSTALLDIR/interface   

                $INSTALL -d $VAMDIR/lib
                $INSTALL -d $VAMDIR/interface
                $INSTALL -C xlib.cma $VAMDIR/lib
                $INSTALL -C xcom.cma $VAMDIR/lib
                $INSTALL -C wxlib.cma $VAMDIR/lib
                $INSTALL -C interface/*.cmi $VAMDIR/interface   
    esac
done
